### PR TITLE
🗺️ feat: Create location query and plot GeoJSON data on map

### PR DESCRIPTION
**Pull request by leamandeep**
@krishnaglodha  I want to notify u that copy EDR URL button isn't copying right url

### CODE REVIEW

**Comment by sourav-rg** [comment]
When I'm runnig the app from the 'main' branch it's showing the pointer properly. like this. 
image
But when I'm running the app from 'pr/1' branch, then it's showing pointers with broken images. Like bellow.
image
Please check this issue.

**Comment by leamandeep** [comment]
Hi @sourav-rg  i got it where i need to fix this part of my code. As krishna said me to plot the data.  Please ping on Discord for further investigation
```js
  const plotGeoJsonOnMap = () => {
    if (mapRef.current) {
      L.geoJSON(geojsonData).addTo(mapRef.current)
    }

  }

  useEffect(() => {
    if (geojsonData) {
      plotGeoJsonOnMap()
    }

  }, [geojsonData])
```

**Comment by leamandeep** [comment]
@sourav-rg  please check my pushed code. I have fix that issue.
image

**Comment by sourav-rg** [comment]
Thanks @elamandeep .  Merged. Please check.

**Pull request merged**
